### ISSUE TITLE
Umbrella: Create a use cases or scenarios for each template

### ISSUE THREAD

**Issue by Zerpet** [Zerpet/docker-rabbitmq-cluster#3]
We have 5 templates so far. We should document how to use each one of them with an example, interesting parts to modify and Compose commands.

- [ ] HA Proxy + 3 Rabbit Nodes
- [ ] 2 disc + 1 RAM Rabbit Nodes
- [ ] 3 Rabbit Nodes
- [ ] Consumer/Producer + 3 Rabbit Nodes
- [ ] Consumer/Producer + HA Proxy + 3 Rabbit Nodes
